..\OBJ\timer.o: ..\HARDWARE\TIMER\timer.c
..\OBJ\timer.o: ..\HARDWARE\TIMER\timer.h
..\OBJ\timer.o: ..\SYSTEM\sys\sys.h
..\OBJ\timer.o: ..\SYSTEM\sys\stm32f10x.h
..\OBJ\timer.o: D:\MDK\ARM\RV31\INC\core_cm3.h
..\OBJ\timer.o: D:\MDK\ARM\RV31\INC\stdint.h
..\OBJ\timer.o: ..\SYSTEM\sys\system_stm32f10x.h
..\OBJ\timer.o: ..\HARDWARE\ULTRASONIC\ultrasonic.h
..\OBJ\timer.o: ..\HARDWARE\INFRARED\infrared.h
..\OBJ\timer.o: ..\SYSTEM\usart\usart.h
..\OBJ\timer.o: D:\MDK\ARM\RV31\INC\stdio.h
..\OBJ\timer.o: ..\HARDWARE\MOTOR\motor.h
..\OBJ\timer.o: ..\HARDWARE\KEY\key.h
..\OBJ\timer.o: ..\HARDWARE\LED\led.h
